@startuml
title Stavový diagram – Monitorování vrat (TOF)

skinparam state {
    BackgroundColor #EEF
    BorderColor black
    ArrowColor black
}

[*] --> ZAVRENO

state ZAVRENO {
    note right
        predchozi_stav = OTEVRENO
        aktualni_stav = ZAVRENO
        cas_otevreni = null
        otevreni_potvrzeno = false
        cas_zavreni = null
        duration = null
    end note
}

state HYSTEREZE {
    note right
        brana_id = naseBrana
        hysteresis_time = now
    end note
}


state OTEVRENO_NEPOTVRZENO {
    note right
        predchozi_stav = ZAVRENO
        aktualni_stav = OTEVRENO
        cas_otevreni = when_created
        otevreni_potvrzeno = false
        cas_zavreni = null
        duration = now - cas_otevreni
    end note
}

state OTEVRENO_POTVRZENO {
    note right
        predchozi_stav = ZAVRENO
        aktualni_stav = OTEVRENO
        cas_otevreni = when_created
        otevreni_potvrzeno = true
        cas_zavreni = null
        duration = now - cas_otevreni
    end note
}

ZAVRENO --> HYSTEREZE : tof_event [state: 1 open]
HYSTEREZE --> HYSTEREZE : tof_event
HYSTEREZE --> OTEVRENO_NEPOTVRZENO : after 3 sec without event
OTEVRENO_NEPOTVRZENO --> OTEVRENO_POTVRZENO : if duration >= threshold
OTEVRENO_POTVRZENO --> ZAVRENO : if otevreni_potvrzeno=true AND aktualni_stav=OTEVRENO
OTEVRENO_NEPOTVRZENO --> ZAVRENO : tof_event [state: 0 close]

@enduml
